services:
  clientemqtt:
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazará por la env var SERVIDOR defineda en .env
      - TOPICOA=${TOPICOA}
      - TOPICOB=${TOPICOB}
      - TOPICOCONTADOR=${TOPICOCONTADOR}
    restart: unless-stopped
